# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 644ba0027c62ac47437323a2ea80c8525b16574fafe1e8cf8013e2f3f51b540cfa70bde8a75854d40a220f285467e8b9fb139bc904443fcb79d8b70d576add81

test:
  secret_key_base: 53779d499b7def9270184d791c86d0f05bce430bddb92dbc1c8959c7f47f146549053529dd6e7ce4e6e7e6e165ac84318023ece9d69548b594c515d7866f7e3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
